#!/usr/bin/env python3

#
# Small helper to run the Docker container specified in the adjacent devcontainer.json file.
#

import json
import os
import re
import subprocess


if __name__ == '__main__':
    docker_path = subprocess.run(
        ['/usr/bin/which', 'docker'],
        stdout=subprocess.PIPE,
        check=True
    ).stdout.strip().decode()

    with open(os.path.join(os.path.dirname(__file__), 'devcontainer.json')) as f:
        container = json.load(f)

        # Perform some adhoc replacement of argument variables
        def env_replace(match):
            return os.environ.get(match.group(1))

        env_re = re.compile(r'\$\{env\:(\w+)\}')
        args = [env_re.sub(env_replace, arg) for arg in container['runArgs']]

        cmd = []
        cmd.append(docker_path)
        cmd.append('run')
        cmd.append('--rm')
        cmd.append('-it')
        cmd.append('--name')
        cmd.append(container['name'])
        cmd.extend(args)
        cmd.append(container['image'])

        print(' '.join(cmd))
        os.execv(cmd[0], cmd)
