load("//toolchain:rules.bzl", "tool_binary")

package(default_visibility = ["//visibility:public"])

tool_binary(
    name = "avy",
    executable = "f2e3044/avy",
)

tool_binary(
    name = "avybmc",
    executable = "f2e3044/avybmc",
)
