# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//toolchain:rules.bzl", "tool_binary")

package(default_visibility = ["//visibility:public"])

tool_binary(
    name = "avy",
    executable = "f2e3044/avy",
)

tool_binary(
    name = "avybmc",
    executable = "f2e3044/avybmc",
)
